+++
author = 'asepsiswu'
title = ".SD 用法"
date = 2020-06-07
archives = "2020/06" 
tags = [ "" ]
summary = ".SD 一些简单用法"
+++

## .SD 的定义
.SD is a data.table containing the Subset of x's Data for each group, excluding any columns used in by (or keyby).

x[i,j,by] 其中x是data.table, .SD是x的一部分。

## 示例数据
```{r}
library(data.table)
DT = data.table(x=rep(c("b","a","c"),each=3), v=c(1,1,1,2,2,1,1,2,2), y=c(1,3,6), a=1:9, b=9:1,key ='x')
DT
X = data.table(x=c("c","b"), v=8:7, foo=c(4,2),key="x")
X
```
## .SD 选择部分column
选择xy变量
```{r}
#第一种方式
DT[, .SD, .SDcols=1:2]   # select columns 'x' and 'y'
#第二种方式
selc = c('x','y')
DT[, .SD, .SDcols=selc]  
#第三种方式
DT[, .SD, .SDcols=x:y]   
#第四种方式
DT[, .SD, .SDcols=patterns('x|y')]                 
#第五种方式
DT[, .SD, .SDcols=grepl('x|y',names(DT))]         
```

## 选择部分行
```{r}
DT[, .SD[1]]             # first row of all columns
DT[, .SD[1], by=x]       # first row of 'y' and 'v' for each group in 'x'
```

## 选择并计算J

```{r}
# .SD 默认是by除外的变量
DT[, c(.N, lapply(.SD, sum)), by=x]    # get rows *and* sum columns 'v' and 'y' by group
DT[, c(.(y=max(y)), lapply(.SD, min)), by=v, .SDcols=v:b]      # compute 'j' for each 'v'
```

## right join
将DT中x为b和c行对应的v值替换为X中值
```{r}
# .SD 实际上是DT[x %in% c('b','c')]
DT[x %in% c('b','c'), X[.SD, v]]
DT[x %in% c('b','c'), X[print(.SD), v]]
DT[x %in% c('b','c'), v:= X[.SD, v]][] 
```
备注： 上述的join默认使用on，on='x',其中on默认的值是data.table的key,也就是'x'


